### ISSUE TITLE
SCRIPT5: access denied in IE

### ISSUE THREAD

**Issue by barnett-kayla** [requirejs/text#105] opened 2015-04-23 16:20 UTC
My webpage uses Durandal which uses RequireJs and the text plugin
Everything works fine if I'm in Chrome/Firefox or if I create a webserver to host the page
However my end application will be an embedded browser so there is no webserver to host the page. The embedded browser is IE and anytime I run my code through IE I get the following error in the console window:
![image](https://cloud.githubusercontent.com/assets/12087249/7301729/14747c30-e9aa-11e4-9692-da41e133ff29.png)
Line 260 is: 
![image](https://cloud.githubusercontent.com/assets/12087249/7301764/5074a2d2-e9aa-11e4-92ac-8fb1c3dae494.png)

This results in the inability to find my html file.
I've looked through posts with similar issues, the only suggestion I found was adding a MoTW, but this didn't seem to do anything to fix the problem.
Any ideas?
Any help would be greatly appreciated, thanks!

**Comment by jrburke** [comment] 2015-04-23 18:18
If the URL being fetched is a file:// URL, there are extra security precautions across browsers around that. For example, I do not think that some browsers allow file:// access to paths that are above or parents of the HTML page doing the request.

So this is not something specific to the text plugin, but sounds like a general XMLHttpRequest issue, and would need to be addressed the same as if a plain XMLHttpRequest was done for the resource. Unfortunately I do not know all the rules IE has in place off the top of my head, but hopefully MSDN has them listed somewhere.

You might be able to avoid the errors by converting the text resources to .js files, which can be done if the text plugin is used in an r.js build. It also means doing some extra setup for some config to pass to the plugin after the build is done, some details in the [XHR restrictions settings](https://github.com/requirejs/text#xhr-restrictions). But I would probably figure out why the XHR did not work in IE as the restriction that blocks it may also block script access.

Closing as a discussion ticket, not a bug fix ticket, but feel free to continue discussion here.

**Closed by jrburke** 2015-04-23 18:18 UTC
